### ISSUE TITLE
Spamfilters: configurable "bad messages" and mass highlight prevention

### ISSUE THREAD

**Issue by Ryan-Goldstein** [jlu5/PyLink#359]
There is no apparent way to preventatively block spam in relayed channels, short of delinking the channel.

As an example, on a PyLink with networks A, B, and C, network A has a spamfilter set to block "spamspamspam" from being sent (via https://www.unrealircd.org/docs/Spamfilter) to a channel that it owns. A user on network C joins the channel and sends "spamspamspam", and it's transmitted and shown to all users in that channel on all networks, even circumventing the spamfilter (with both shun and block actions) on network A.

Would it be possible for PyLink to either parse and enforce the spamfilters on the linked networks respectively (e.g. by blocking matching messages from being sent to channels/users on the network on which they were set), or maybe add a 'badwords' or similar setting to PyLink to allow the network staff to specify words/phrases that should not be transmitted from a relay network to channels and/or users on the local network, such as: https://www.unrealircd.org/docs/Badword_block

Thanks!

edit 2018-04-07 by @GLolol: see https://github.com/GLolol/PyLink/issues/359#issuecomment-378819491 for a proposed fix

**Comment by jameswritescode** [comment]
It'd be pretty slick if PyLink could both support the spamfilter for the IRCd as well as it's own spamfilter system.

**Comment by GLolol** [comment]
FWIW I'd have to look into how spamfilter data is passed between servers (it'll probably be different for every IRCd).

**Comment by GLolol** [comment]
Alternatively, we could just block bad text at the Relay level (configured this way as well), and separate it from IRCd-specific spamfilter settings that probably wouldn't sync well...

**Comment by GLolol** [comment]
Here's how I'll do this for 2.0:

- [ ] Introduce a `spamserv` plugin capable of monitoring preconfigured channels. Channel persistence is still sort of a sore point due to #265, so that needs to be resolved first.
- [ ] Implement block / kill on mass highlight
- [ ] Implement blocking of messages matching arbitrary preconfigured globs (maybe extend to regex in the future if I can find a high-performance way to do it)

This implementation will be completely independent of IRCd-side spamfilters, which don't exist on all IRCds and don't behave consistently on the ones that do support it. [this level of integration will be a wontfix]

Also, this can be its own plugin completely since #547 is complete in 2.0!
