### ISSUE TITLE
Disable service bot spawning for Clientbot properly, instead of simply stubbing spawnClient()

### ISSUE THREAD

**Issue by jlu5** [jlu5/PyLink#403]
- [x] Allow toggling service spawning globally and per-service.
- [ ] Disable service spawning where it's not supported (prerequisite: #337)

**Comment by GLolol** [comment]
The above commits (a776aab, 75b5be5, feb9cce, 90d3ac3) *partially* fix this by removing service client stubs on Clientbot and making service spawning optional per-service. However, because ServiceBot instances are global, it's not yet possible to rebind commands for a service client to the main client on a per-network basis.
