### ISSUE TITLE
UTF-8 nicks support in relay

### ISSUE THREAD

**Issue by janicez** [jlu5/PyLink#561]
I run an IRC network that supports UTF8 nicknames, so using Pylink may cause issues not expected on networks supporting only 10646 nicknames.

**Comment by GLolol** [comment]
UTF8 nicks isn't something I've tested. If nothing else breaks before leading to that point, Relay in particular will replace all non-IRC characters with a fallback separator "|":

https://github.com/GLolol/PyLink/blob/9dfa0a478e77f18ce1d58ab4e8c1347f0d76935a/plugins/relay.py#L156-L160

This is probably not an elegant result, but that bit of code is targeted towards normalizing separators in nicks (e.g. "/" isn't supported everywhere), and not towards dealing with other character spaces.

I have my own questions at this point:
- Is there a standard for UTF-8 nicks and how they should be dealt with at a server level? What about [homographs](https://en.wikipedia.org/wiki/IDN_homograph_attack) and invisible control characters such as `/nick \x03`?
- Are you referring to an actual mainstream IRCd implementing UTF-8 in nicks, or is this some IRCd fork with every sanity check disabled? I have absolutely no interest in supporting the latter because it's niche and takes way too much effort to properly test.

**Comment by janicez** [comment]
This is some fork, but it does have some sanity checks (no spaces allowed, still). Homographs and invisibles are treated as "tough noogies" (presumably allowed).

**Comment by janicez** [comment]
19:09:53     umbr -- Very<c3>flickable</c>: Erroneous Nickname

Tested, it doesn't allow colours, apparently. It's been a while since I've dug through match.c.

**Comment by xnite** [comment]
@GLolol the way you handle the nicknames (from the way I understand your explaination) could cause nick collisions if say for example someone has the nick ă̵̛̛͖̖̲̬̘̳̰̱͇̹̺̅̾̈́̕͝ and someone else has the nick b̶̨̡͉̪͉͕̻̙̪̭̂.  Please correct me if I'm wrong.

**Comment by GLolol** [comment]
Modified IRCds are not supported.

Regarding UTF-8 nicks in general, I'd rather wait until a proper standard has been implemented instead of jumping the gun and opening up a world of spoofing attacks.

----
@xnite Hence why this isn't really supported.

(As another detail, if relay hits a nick collision for a tagged nick, it'll go from `person1/net1 -> person1//net1` all the way until you run out of spaces for nicks. Then it'll start truncating the actual nick: `blahblah/net1 -> blahbla//net1 -> blahbla///net1`)

**Comment by janicez** [comment]
Stop making me laugh so hard...

sorry
