### ISSUE TITLE
Multiple UIDs found for nick -> Log spam

### ISSUE THREAD

**Issue by Miniontoby** [jlu5/PyLink#665]
Hi, 

I got an PyLink relay on my network and got a lot of log spam:

for example: 
```
[WARNING] (mynet) Multiple UIDs found for nick 'chanserv': ['ChanServ@704', 'ChanServ@1209', 'ChanServ@1445', 'ChanServ@2232', 'Chan
Serv@3304', 'ChanServ@3484', 'ChanServ@4497', 'ChanServ@4712', 'ChanServ@5245', 'ChanServ@5888', 'ChanServ@7127', 'ChanServ@7458']; using the last one!
```
but it is with all nicks

My question: How to fix this log??

and Second question:

at my other network where i also did it as non-clientbot i see nicks like:
```Miniontoby|mynet, Miniontoby||mynet, Miniontoby|||mynet, Miniontoby||||mynet```

How to fix these?

Greets Miniontoby

**Comment by jlu5** [comment]
What IRCds do you have set up on your instance? And what IRCd is clientbot connecting to?

**Comment by Miniontoby** [comment]
ngircd at mynet, and at the other one too

**Comment by jlu5** [comment]
Is there any particular action that triggers this bug? e.g. does it happen consistently after startup, after joining a particular channel, ...

Can you try to reproduce the bug after [enabling debug mode](https://github.com/jlu5/PyLink/blob/master/example-conf.yml#L679-L682) and attach the log somewhere? Since this may include sensitive data (server passwords, IPs, etc) feel free to send me PGP encrypted mail (key: `D5D568B2D34AB32A337944D22EC3F60DE71C0B9D`) or DM me a link on IRC.

**Comment by jlu5** [comment]
Today I read on the [ircnow wiki](https://wiki.ircnow.org/index.php?n=Debate.WhyC) that they want to "[phase] out" PyLink "with a custom bot built either by forking eggdrop or forked from ii/sic" in hopes of creating a "true citizen militia". In this spirit of [dogfooding](https://wiki.ircnow.org/index.php?n=Debate.Dogfooding) this is an invitation to please do so and share your lovely creations with the world.

As a developer, I will not waste my time helping any organization that holds such [extreme](https://archive.is/M0uDr), [arbitrary](https://wiki.ircnow.org/index.php?n=Debate.Python), and flat out [contradictory](https://wiki.ircnow.org/index.php?n=Debate.Firstamendment) opinions. You are free to hold whatever views you want, but I'm not going to help you.
