### ISSUE TITLE
PyLink S2S protocol - Something that could mimic InterJanus

### ISSUE THREAD

**Issue by jlu5** [jlu5/PyLink#99]
Some things that would be needed:
- [ ] Decide on a basic format for the protocol - I'm thinking of something based on JSON, but not sure yet
- [ ] Authentication (sendpass, recvpass, possibly SSL/TLS certificate fingerprints)
- [ ] Delivering hook payloads over the protocol - plugins bind themselves to events via the hook system like they do already

**Comment by GLolol** [comment]
From https://github.com/GLolol/PyLink/issues/144#issuecomment-167169335: The goal is to integrate Clientbot with the S2S protocol so that instead of PyLink doing connections directly via client-to-server code, existing bot frameworks (supybot, eggdrop, etc.) can be used to go into channels and forward what it sees to PyLink daemon(s) via a S2S protocol. But I'm still thinking about how to structure such a protocol to be extensible and efficient.
